---
title: "homework-week-4_Rmd"
output: html_document
---
#Homework Week 4

##HW Problem 1 (a)
```{R, echo=TRUE}
X<-8
l<-15
prob_a<-1-ppois(q=X,lambda=l)
prob_a
```
##HW Problem 1 (b)
```{R,echo=TRUE}
X<-0
l<-15
prob_b<-dpois(x=X,lambda = l)
prob_b
```
##HW Problem 1 (c)
```{R,echo=TRUE}
X<-3
l<-15
prob_c<-dpois(x=X,lambda = l)
prob_c
```
##HW Problem 1 (d)
```{R,echo=TRUE}
barplot(dpois(x=0:30,lambda=15),names.arg=0:30,space=0,xlab="Number of Calls Heard (x)",ylab="Pr(X = x)")
```
##HW Problem 1 (e/f)
```{R,echo=TRUE}
titi_calls <- rpois(n=104,lambda = 15)
head(titi_calls)
hist(titi_calls,xlim=c(0,30),probability = T,xlab="# of calls",ylab ="Frequency",main = "Histogram of Titi calls (simulated dataset:n=104)")
```
The charts differ in two main ways. Firstly, the barplot created in 1d shows a much more normal distribution than the histogram produced in 1e/f. Additionally, the mean and variance are both much greater for the simulated data from part 1e. I believe-though this interpretation may be incorrect!-that this is due to the fact that the histogram is plotting the density/frequency of hearing a certain # of calls during each of the 104 trials whereas the barplot is illustrating the probability (based on the Poisson distribution), that x number of calls would be heard in any random trial... However, I'm still a bit fuzzy on this interpretation so Tony, I'll definitely be seeing you next week to review a couple of things!